<div class="container-login">
    <div class="img-box">
        <img src="<?php echo $this->basePath('img/login.svg'); ?>">
    </div>
    <div class="content-box">
        <div class="form-box">
            <h2>Login</h2>
            <form>
                <div class="input-box">
                    <span>Username</span>
                    <input type="email" placeholder="@mail.com">
                </div>

                <div class="input-box">
                    <span>Password</span>
                    <input type="password" placeholder="password">
                </div>

                <div class="input-box">
                    <input type="submit" value="Entrar">
                </div>

            </form>
        </div>
    </div>
</div>