<!-- BEGIN CONTAINER -->
<div class="row" ng-controller="AuthCtrl">
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
            <div class="card-body">
                <div class="alert alert-danger text-justify">
                    <p><?php echo $this->translate('You need to upgrade your account to access this feature.');?></p>
                    <p><?php echo $this->translate('There are plenty of reasons you might want to upgrade your account. Whether you want access to pro-level features or just want to switch to new interface.');?></p>
                    <p class="text-uppercase font-weight-bold"><?php echo $this->translate('Some features are incompatible between versions.');?></p>
                    <p><?php echo $this->translate('To CONFIRM the upgrade, please enter your username and password again.');?></p>
                </div>
                <form name="myForm" id="myForm" novalidate>
                    <div class="form-group">
                        <label class="small"><?php echo $this->translate('Username');?></label>
                        <input type="text" id="username" name="username" class="form-control form-control-lg" placeholder="<?php echo $this->translate('Username');?>" required autofocus minlength="3" maxlength="100"  ng-model="form.username" />
                        <small id="usernameHelpBlock" class="form-text text-muted" ng-show="myForm.username.$error.required"><?php echo $this->translate(' Please enter your username.');?></small>
                    </div>

                    <div class="form-group" ng-cloak>
                        <label for="password" class="small"><?php echo $this->translate('Password');?></label>
                        <div class="input-group">
                            <input type="password" id="password" name="password" class="form-control form-control-lg" placeholder="Password" required maxlength="20" min="7" ng-model="form.password" ng-attr-type="{{ showPassword ? 'text' : 'password' }}"/>
                            <div class="input-group-append"><button class="btn" type="button" ng-class="showPassword ? 'btn-warning' : 'btn-outline-secondary'" ng-click="showPassword=!showPassword" autofocus="autofocus"><i ng-class="showPassword ? 'far fa-eye' : 'far fa-eye-slash'"></i></button></div>
                        </div>
                    </div>
                    <button class="btn btn-lg btn-danger btn-block text-uppercase" type="button" ng-click="accepted();" ng-disabled="myForm.$invalid"><?php echo $this->translate('I Accept');?></button>

                    <a href="<?php echo $this->url('login', ['action' => 'logout'], ['force_canonical' => true]); ?>" role="button" class="btn btn btn-secondary btn-block text-uppercase"><?php echo $this->translate('Not Accepted');?></a>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- END CONTAINER -->