<!--begin::Body-->
<div class="d-flex flex-column flex-lg-row-fluid py-10" ng-controller="AuthCtrl"ng-init="submitPassword();">
    <!--begin::Content-->
    <div class="d-flex flex-center flex-column flex-column-fluid">
        <!--begin::Wrapper-->
        <div class="w-lg-500px p-10 p-lg-15 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <a href="<?php echo $this->url('home', ['action' => 'index'], ['force_canonical' => true]); ?>">
<!--                        <img src="--><?php //echo $this->basePath('img/logo-2018.png'); ?><!--" class="img-fluid mx-auto d-block m-2 w-75 "/>-->
                    </a>

                    <div class="col-12">
                        <p><h4><?php echo $this->CALCULOIDEAL_RESET_MESSAGE; ?></h4></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>