<div class="row" ng-controller="AuthCtrl">
<!--    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">-->
        <div class="card card-signin my-5">
            <div class="card-body">
<!--                <span class="text-uppercase font-weight-bold btn btn-warning btn-block rounded-0 animated flash disabled mb-2">--><?php //echo $this->translate('14-day free trial');?><!--</span>-->
                <form name="myForm" id="myForm" novalidate>
                    <!-- BEGIN FORM -->
<!--                    <div class="form-row">-->
<!--                        <span class="col-12 small text-muted text-right"><a href="https://youtu.be/21FFA30cwbA" target="_blank">--><?php //echo $this->translate('Help');?><!--?<i class="far fa-question-circle mb-0 mt-0 mr-2 ml-2"></i></a></span>-->
<!--                    </div>-->

                    <div class="form-row">
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label for="name" class="small"><?php echo $this->translate('Name');?></label>
                            <input type="text" class="form-control " id="name" name="name" placeholder="<?php echo $this->translate('Name');?>" required maxlength="100" ng-model="form.name" autofocus>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="name" class="small"><?php echo $this->translate('Surname');?></label>
                            <input type="text" class="form-control " id="surname" name="surname" placeholder="<?php echo $this->translate('Surname');?>" required maxlength="100" ng-model="form.surname" autofocus>
                        </div>
                    </div>
                    </div>

                    <div class="form-row row">
                        <div class="form-group col-md-6">
                            <label for="email" class="small"><?php echo $this->translate('Email');?></label>
                            <input type="email" class="form-control " id="email" name="email" placeholder="<?php echo $this->translate('Email');?>" required maxlength="300" ng-model="form.email">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="username" class="small"><?php echo $this->translate('Username');?></label>
                            <input type="text" class="form-control" id="username" name="username" placeholder="<?php echo $this->translate('Username');?>" required ng-model="form.username" maxlength="20" minlength="3">
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label for="senha" class="small"><?php echo $this->translate('Password');?></label>
                            <div class="input-group">
                                <input type="password" id="password" name="password" class="form-control form-control-lg" placeholder="Password" required maxlength="20" min="7"
                                       ng-model="form.password" ng-attr-type="{{ showPassword ? 'text' : 'password' }}"/>
                                <div class="input-group-append">
                                    <button class="btn" type="button" ng-class="showPassword ? 'btn-warning' : 'btn-outline-secondary'" ng-click="showPassword=!showPassword" autofocus="autofocus">
                                        <i ng-class="showPassword ? 'far fa-eye' : 'far fa-eye-slash'"></i>
                                    </button></div>
                            </div>
                            <small id="passwordHelpBlock" class="form-text text-muted" ng-show="myForm.password.$error.required"><?php echo $this->translate('Your password must be 8 & up; 20 characters.');?></small>
                        </div>
                    <div class="form-group col-md-12">
                            <label for="senha" class="small"><?php echo $this->translate('Confirm password');?></label>
                            <div class="input-group">
                                <input type="password" id="passwordConf" name="passwordConf" class="form-control form-control-lg" placeholder="Password" required maxlength="20" min="7"
                                       ng-model="form.passwordConf" ng-attr-type="{{ showPassword ? 'text' : 'password' }}"/>
                                <div class="input-group-append">
                                    <button class="btn" type="button" ng-class="showPassword ? 'btn-warning' : 'btn-outline-secondary'" ng-click="showPassword=!showPassword" autofocus="autofocus">
                                        <i ng-class="showPassword ? 'far fa-eye' : 'far fa-eye-slash'"></i>
                                    </button></div>
                            </div>
                        </div>
                    </div>
                    <!-- END FORM-->
                    <div class="form-group mt-2 mb-4">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="tnc" name="tnc" required ng-model="form.tnc">
                            <label class="form-check-label text-warning" for="tnc"><?php echo $this->translate('I agree to the Terms of Service and Privacy Policy .');?></label>
                        </div>
                    </div>
                    <button type="button" class="btn btn-occurrence text-uppercase col-lg-5 col-md-6 col-sm-6 col-xs-12 mb-1 no-show-during-spinner"
                            ng-click="signUp();" ><i class="fas fa-check mr-2"></i><?php echo $this->translate('Submit');?></button>
                    <a href="<?php echo $this->url('login',['action'=>'index'],['force_canonical' => true]); ?>" class="btn btn-secondary text-uppercase float-lg-right float-md-right col-lg-5 col-md-5 col-sm-5 col-xs-12 no-show-during-spinner" role="button"><i class="fas fa-chevron-left mr-2"></i><?php echo $this->translate('Back');?></a>
                </form>
            </div>
        </div>
<!--    </div>-->
</div>