<!-- Navbar Start -->
<div class="container-fluid bg-light position-relative shadow">
    <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0 px-lg-5">
        <a href="" class="navbar-brand font-weight-bold text-secondary" style="font-size: 50px;">
            <img src="<?php echo $this->basePath('img/favicon.ico'); ?>" height="50" width="50">
            <span class="text-primary">BiblioTech</span>
        </a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
            <div class="navbar-nav font-weight-bold mx-auto py-0">
                </div>
            <a href="" class="btn btn-primary px-4">Entrar</a>
        </div>
    </nav>
</div>
<!-- Navbar End -->

<!-- Header Start -->
<div class="container-fluid bg-primary px-0 px-md-5">
    <div class="row align-items-center px-3">
        <div class="col-lg-6 text-center text-lg-left">
            <h4 class="text-white mb-4 mt-5 mt-lg-0">Rabindranath Tagore Dos Santos Pires Emef</h4>
            <h1 class="display-3 font-weight-bold text-white">Conhecimento em Movimento</h1>
            <p class="text-white mb-4">
                Um sistema de biblioteca escolar eficiente é uma ferramenta fundamental para o
                aprendizado e desenvolvimento dos alunos. Ao organizar e disponibilizar recursos
                educacionais, desde livros até materiais multimídia, esse sistema promove o acesso
                igualitário ao conhecimento. Além disso, ao oferecer serviços como empréstimos e
                reservas, ele incentiva a leitura e pesquisa, contribuindo para o crescimento
                intelectual da comunidade escolar.</p>
            <a href="" class="btn btn-secondary mt-1 py-3 px-5">Venha conhecer</a>
        </div>
        <div class="col-lg-6 text-center text-lg-right">
            <img class="img-fluid mt-5" src="<?php echo $this->basePath('img/header.png'); ?>" alt="">
        </div>
    </div>
</div>
<!-- Header End -->



<!-- Blog End -->